version: '3'

services:
    nginx:  # Nginx reverse proxy server
        image: nginx:latest
        container_name: covidresearch-backend-nginx
        ports:
            - "10080:80"
        volumes:
            - ./src:/src
            - ./config/nginx:/etc/nginx/conf.d
        depends_on:
            - backend

    backend:  # Python Django backend
        image: backend
        container_name: covidresearch-backend
        build:
            context: covidsearch_backend
            dockerfile: Dockerfile
        command: ./run_backend.sh
        ports:
            - "5000:5000"
        depends_on:
            - elasticsearch
            - redis
        environment:
            - ES_HOST=elasticsearch
            - ES_PORT=9200
            - ES_JAVA_OPTS="-Xms2g -Xmx2g" ./bin/elasticsearch
        expose:
            - "5000"

    elasticsearch: # Elasticsearch Instance
        container_name: covidresearch-search
        image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
        volumes: # Persist ES data in seperate "esdata" volume
            - esdata:/usr/share/elasticsearch/data
        environment:
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
            - discovery.type=single-node
            - http.max_content_length=200mb
        ports: # Expose Elasticsearch ports
            - "9300:9300"
            - "9200:9200"

    redis:
        container_name: covidresearch-redis-broker
        image: redis:latest
        ports:
            - "6379:6379"

volumes:  # Define separate volume for elasticsearch data (research papers)
    esdata:
