version: '3'

services:
    nginx:  # Nginx reverse proxy server
        image: nginx:latest
        container_name: covidresearch-backend-nginx
        ports:
            - "10080:80"
        volumes:
            - ./src:/src
            - ./config/nginx:/etc/nginx/conf.d
        depends_on:
            - backend

    backend:  # Python Django backend
        image: backend
        container_name: covidresearch-backend
        build:
            context: covidsearch_backend
            dockerfile: Dockerfile
        command: ./run_backend.sh
        ports:
            - "5000:5000"
        depends_on:
            - elasticsearch
            - redis
        environment:
            - ES_HOST=elasticsearch
            - ES_PORT=9200
        expose:
            - "5000"

    worker:  # Worker to run asynchronous tasks
        image: backend
        container_name: covidresearch-backend-worker
        command: rqworker --url ${BROKER_URL}
        # env_file:
            # ./config/project_vars.env.dev
        environment:
            - BROKER_URL=${BROKER_URL}
        depends_on:
            - backend
            - redis
        links:
            - redis

    scheduler:  # Scheduler to run cron job of parsing rss feeds
        image: backend
        container_name: covidresearch-backend-scheduler
        command: rqscheduler --host ${REDIS_HOST} --port ${REDIS_PORT} --interval ${NUM_SECS}
        # env_file:
            # ./config/project_vars.env.dev
        environment:
            - REDIS_HOST=${REDIS_HOST}
            - REDIS_PORT=${REDIS_PORT}
            - NUM_SECS=${NUM_SECS}
        depends_on:
            - backend
            - redis
        links:
            - redis

    elasticsearch: # Elasticsearch Instance
        container_name: covidresearch-search
        image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
        volumes: # Persist ES data in seperate "esdata" volume
            - esdata:/usr/share/elasticsearch/data
        environment:
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - discovery.type=single-node
        ports: # Expose Elasticsearch ports
            - "9300:9300"
            - "9200:9200"

    redis:
        container_name: covidresearch-redis-broker
        image: redis:latest
        ports:
            - "6379:6379"

volumes:  # Define separate volume for elasticsearch data (research papers)
    esdata:
