version: '3'

services:
    nginx:  # Nginx reverse proxy server
        image: nginx:latest
        container_name: covidresearch-backend-nginx
        ports:
            - "10080:80"
        volumes:
            - ./src:/src
            - ./config/nginx:/etc/nginx/conf.d
        depends_on:
            - backend

    backend:  # Python Django backend
        container_name: covidresearch-backend
        build:
            context: covidsearch_backend
            dockerfile: Dockerfile
        command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && gunicorn covidsearch_backend.wsgi -b 0.0.0.0:5000 -w 4"
        ports:
            - "5000:5000"
        depends_on:
            - elasticsearch
        environment:
            - ES_HOST=elasticsearch
            - ES_PORT=9200
        expose:
            - "5000"

    elasticsearch: # Elasticsearch Instance
        container_name: covidresearch-search
        image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
        volumes: # Persist ES data in seperate "esdata" volume
            - esdata:/usr/share/elasticsearch/data
        environment:
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - discovery.type=single-node
        ports: # Expose Elasticsearch ports
            - "9300:9300"
            - "9200:9200"

volumes:  # Define separate volume for elasticsearch data (research papers)
    esdata:
